<br>
<br>
**<font size=5><center>Predicting Default Rates for Lending Club</center></font>**

### Authors:

<font size=5>Devon Luongo</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>deluongo@gmail.com</font> <br>

<font size=5>Ben Yuen</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>benyuen@hotmail.com</font> <br>

<font size=5>Bryn Clarke</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3></font>clarke.bryn@gmail.com<br>

<font size=5>Ankit Agarwal</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>ankit.frnz@gmail.com</font> <br>

**<font size=4><center>Abstract</center></font>**

<center>**!!(Insert Abstract)!!**</center>

# I. Introduction

Lending Club is an online marketplace that fascilitates the lending money to individuals or businesses through online services that match lenders directly with borrowers. This practice is called Peer-to-Peer (P2P) Lending. With an A+ BBB rating, Lending Club offers an attractive alternative to bonds for steady investment income. Lending Club also states that borrowers are able to reduce their loans by an average of 30%.

"Since peer-to-peer lending companies offering these services operate entirely online, they can run with lower overhead and provide the service more cheaply than traditional financial institutions. As a result, lenders often earn higher returns compared to savings and investment products offered by banks, while borrowers can borrow money at lower interest rates, even after the P2P lending company has taken a fee for providing the match-making platform and credit checking the borrower."

The downside to Lending Club however, is that most peer-to-peer loans are unsecured personal loans, meaning lenders incur a higher risk than comparable steady income investments like Treasury Bonds. Therefore, the investment quality of each loan depends largly on three factors: the expected return, the level of risk aversion, and the risk incurred. The first factor is built into the contract of the loan, and the second factor is personal preference. Therefore, the primary variable that that investors must identify when compoaring P2P Lending with other investment opportunities is the default risk for each loan. 

For this reason, Lending Club offers lenders a dataset containing a comprehensive list of features that can be employed to make better lending decisions. Detailed information for every loan have been issued by Lending Club from 2007 to 2015. Among**!!(Insert Num Predictors)!!** features or predictors in total, the dataset includes a borrowerâ€™s annual incomes, zip codes, revolving balances, and purpose for borrowing.

Our objective was to build on similar projects conducted in recent years to construct a model for default risk to help lenders decrease the risk they occur when lending. We trained and tested a range of models in an attempt to identify the best performing model. Additionally, we constructed a cost based model aimed at maximizing Lending Clubs overhead.

# II. Related Work

**!!(Rewrite After Models Complete)!!** 
Prior projects like **!!("Predicting borrowers chance of defaulting on credit loans" [1])!!** have set great examples of applying machine learning to improve loan default prediction in a Kaggle competition, and authors for**!!("Predicting Probability of Loan Default" [2])!!**  have shown that Random Forest appeared to be the best performing model on the Kaggle data. 

However, despite the early success using Random Forest for default prediction, real-world records often behaves differently from curated data, and a later study **!!("Peer Lending Risk Predictor" [3])!!** presented that a modified Logistic Regression model could outperform SVM, Naive Bayes, and even Random Forest on Lending Club data. 

The fact that Logistic Regression performance could be immensely improved by simply adding penalty factor on misclassification gave rise to our interest in fine tuning other not-yet optimized models, in particular, SVM and Naive Bayes, to continue the search for a better predictive model in the realm of loan default. Besides the difference in types of model that they focus on, the prior studies only used the out-of-the-box dataset from Kaggle or
Lending Club, but research like **!!("The sensitivity of the loss given default rate to systematic risk" [4])!!** has shown the linkage between default rate and macroeconomic factors, so we have decided to add in census data, with info like regional median income, to train our models on a more holistic set of features.

# III. Data

### Data Preparation

*Libraries*

In [1]:
import pandas as pd
import numpy as np

Some of the data files have fields that contain NAs for older time periods. In order to collapse the data sets into one file, all numerical data will be stored in float fields (integer fields do not support NA missing values). To do this, we first define a conversion dictionary that stores the numeric fields with lookups to the *float* data type.

In [2]:
convert_float = dict([s, float] for s in
                     ['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'installment',
                      'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'mths_since_last_delinq',                      
                      'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
                      'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
                      'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
                      'last_pymnt_amnt', 'collections_12_mths_ex_med', 'mths_since_last_major_derog',
                      'annual_inc_joint', 'dti_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 
                      'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 
                      'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 
                      'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 
                      'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
                      'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
                      'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc',
                      'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq',
                      'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 
                      'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
                      'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
                      'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
                      'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
                      'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'])

We also define a dictionary of string fields, to handle situations where the inferred data type might be numeric even though the field should be read in as a string/object.

In [3]:
convert_str = dict([s, str] for s in
                    ['term', 'int_rate', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 
                     'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 
                     'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util', 
                     'initial_list_status', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d',
                     'policy_code', 'application_type', 'verification_status_joint'])

We also define a dictionary of string fields, to handle situations where the inferred data type might be numeric even though the field should be read in as a string/object.

In [4]:
convert_categ = dict([s, "categorical"] for s in
                      ["term", "grade", "sub_grade", "home_ownership", "emp_length",
                       "verification_status", "loan_status", "pymnt_plan", "purpose", "addr_state",
                       "initial_list_status", "policy_code", "application_type", "verification_status_joint"])

We read the input data from the CSV data files using pandas *read_csv*. There is a blank row in the data header and there are two blank rows in the footer of each file. To allow the use of *skip_footer*, we use the python engine rather than the C engine. The first two columns (*id* and *member_id*) are unique and used to create a table index.

In [5]:
def read_data(file_loc):
    data = pd.read_csv(file_loc,
                       skiprows=1,
                       skip_footer=2,
                       engine="python",
                       na_values=['NaN', 'nan'],
                       converters=convert_str,
                       index_col=[0,1])
    
    # Depending on the specific dataset used, the numeric values may be read in as integers.
    # For best performance and to enable mergining of the datasets, we convert those fields
    # to floats (which allow NaN values):
    for k, v in convert_float.items():
        data[k] = data[k].astype(v)
    
    # There are 5 object fields that contain dates in the format *YYYY-MMM* (e.g. '2010-Jan').
    # We parse those to return datetime fields, which are more easily input into time series models
    # or plotted in charts.
    data.issue_d = pd.to_datetime(data.issue_d, errors="coerce")
    data.last_pymnt_d = pd.to_datetime(data.last_pymnt_d, errors="coerce")
    data.next_pymnt_d = pd.to_datetime(data.next_pymnt_d, errors="coerce")
    data.last_credit_pull_d = pd.to_datetime(data.last_credit_pull_d, errors="coerce")
    data.earliest_cr_line = pd.to_datetime(data.earliest_cr_line, errors="coerce")
    
    return data

data = pd.concat([read_data(s) for s in ["./data/LoanStats3a.csv", "./data/LoanStats3b.csv", "./data/LoanStats3c.csv", "./data/LoanStats3d.csv"]])

In [6]:
print data.shape

(887441, 109)

Many of the remaining fields contain categorical data. We use the pandas *category* data type to store the data more efficiently.

In [7]:
for k, v in convert_categ.items():
    data[k] = pd.Categorical(data[k])

Some percentages are stored as strings (*int_rate*, *revol_util*). Here we convert them into a float by stripping the % symbol and dividing by 100.

In [8]:
def percent_to_float(s):
    if (type(s) == str):
        if ("%" in s):
            return float(str(s).strip("%"))/100
        else:
            if s == "None":
                return np.nan
            else:            
                return s
    else:
        return s

data.int_rate = [percent_to_float(s) for s in data.int_rate]
data.revol_util = [percent_to_float(s) for s in data.revol_util]

In [9]:
# The remaining 5 object type fields are dropped as they aren't easily incorporated in a design matrix
data = data.drop(["emp_title", "url", "desc", "title", "zip_code"], axis=1)

In [10]:
# We decided to convert the date fields to the number of days since 1/1/1900
for date_col in ["issue_d", "earliest_cr_line", "last_pymnt_d", "next_pymnt_d", "last_credit_pull_d"]:
    data.loc[:, date_col] = (data.loc[:, date_col] - pd.to_datetime("1/1/1900")).dt.days

In [11]:
# Let us see what status we have.
print data["loan_status"].value_counts()

Current                                                467679
Fully Paid                                             315192
Charged Off                                             75740
Late (31-120 days)                                      14548
In Grace Period                                          8432
Late (16-30 days)                                        2968
Does not meet the credit policy. Status:Fully Paid       1988
Does not meet the credit policy. Status:Charged Off       761
Default                                                   132
None                                                        1
Name: loan_status, dtype: int64

In [12]:
# Ok we dont want current or None status as we don't know what is going to happen with those.
# next also late and grace period we are not sure about.
# thirdly we remove loans that do not meet credit policy so we can convert our issue to a binar model
data = data[((data["loan_status"] == "Default") | (data["loan_status"] == "Charged Off") | (data["loan_status"] == "Fully Paid"))]

# Rename "Charged off to default"
data["loan_status"] = data["loan_status"].replace("Charged Off", "Default")
data["loan_status"] = data["loan_status"].replace("Default", 1)
data["loan_status"] = data["loan_status"].replace("Fully Paid", 0)
print data.shape
print data["loan_status"].value_counts()

(391064, 104)
0    315192
1     75872
Name: loan_status, dtype: int64

In [13]:
# There are only 50 joint applications, so we coalesce the fields that have joint values (annual_inc, dti, verification_status)
for joint_col in ["annual_inc", "dti", "verification_status"]:
    data.loc[data.application_type=="Joint", joint_col] = data.loc[data.application_type=="Joint", joint_col + "_joint"]

data = data.drop(["annual_inc_joint", "dti_joint", "verification_status_joint"], axis=1)

In [14]:
# policy_code has only one level, "1", and pymnt_plan is all "N" except for 4 records so we drop both 
data = data.drop(["pymnt_plan", "policy_code"], axis=1)

In [15]:
# While grade and sub_grade are thought to be predictive, they use Lending Tree's credit model and we don't
# want to influence our scoring model using their model that will capture much of the same information
# This is also true of int_rate and installment, which are each correlated with LT's credit grade
data = data.drop(["int_rate", "installment", "grade", "sub_grade"], axis=1)

In [16]:
# Finally we drop other fields that are not known a priori and may contain information
# post-default / delinquency that will bias our results
# This includes payment history and loan balances
data = data.drop(["out_prncp", "out_prncp_inv", "total_pymnt", "total_pymnt_inv", "total_rec_prncp",
                  "total_rec_int", "total_rec_late_fee", "recoveries", "collection_recovery_fee",
                  "last_pymnt_d", "last_pymnt_amnt", "next_pymnt_d", "last_credit_pull_d"], axis=1)

In [17]:
print "Pearson correlation between [%s] and [%s]: %.3f" % ("funded_amnt", "funded_amnt_inv", np.corrcoef(data.funded_amnt, data.funded_amnt_inv)[0,1])

Pearson correlation between [funded_amnt] and [funded_amnt_inv]: 0.997

In [18]:
# There is nearly perfect correlation between funded_amnt and funded_amnt_inv, so we remove funded_amnt_inv
data = data.drop(["funded_amnt_inv"], axis=1)

In [19]:
#import quandl
state_list = ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL",
              "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA",
              "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE",
              "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI",
              "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV",
              "WY"]
#state_unemployment_data = {}
#for i in state_list:
#    try:
#        print(i)
#        result = quandl.get('FRED/{:s}UR'.format(i))
#        state_unemployment_data[i] = result
#    except RuntimeError as e:
#        print(e)

#check all indices are sorted by date
#for s in state_unemployment_data.keys():
#    if not state_unemployment_data[s].index.is_monotonic:
#        print s

#convert percentages to a value in the range [0, 1]
#for s in state_unemployment_data.keys():
#    state_unemployment_data[s]['VALUE'] = state_unemployment_data[s]['VALUE'] / 100.0

#import pickle
#with open('unemployment_rates_by_state.pkl', 'wb') as f:
#    pickle.dump(state_unemployment_data, f)

In [20]:
import pickle
with open('unemployment_rates_by_state.pkl', 'rb') as f:
    state_unemployment_data = pickle.load(f)

In [21]:
def get_state_unemp_df(s):
    unemp_data = state_unemployment_data[s]
    unemp_data = unemp_data.rename(columns={'VALUE':s})
    return unemp_data

df_unemp = pd.concat([get_state_unemp_df(s) for s in state_list], axis=1)
df_unemp.index = (pd.to_datetime(df_unemp.index) - pd.to_datetime("1/1/1900")).days

In [22]:
def lookup_unemp(issue_date, state):
    try:
        result = df_unemp.loc[issue_date, state]
    except:
        result = np.na
    return result

data.state_unemp_rate = [lookup_unemp(issue_date, state) for issue_date, state in zip(data.issue_d, data.addr_state)]

In [23]:
df_y = data["loan_status"]
df_X = data.drop("loan_status", axis=1)
# Remove member id.
df_X = df_X.ix[:, 1:]

In [24]:
print df_X.shape
print df_y.shape

(391064, 79)
(391064,)

In [25]:
for k, v in convert_categ.items():
    if not(k in ["verification_status_joint", "policy_code", "grade", "sub_grade", "pymnt_plan", "loan_status"]):
        df_X = pd.concat([df_X,
                          pd.get_dummies(df_X[k], prefix=k)],
                         axis=1)
        df_X = df_X.drop(k, axis=1)

In [26]:
df_X

,,funded_amnt,annual_inc,issue_d,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,...,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY
id,member_id,,,,,,,,,,,,,,,,,,,,,
1077501,1296599.0,5000.0,24000.00,40876.0,27.65,0.0,31046.0,1.0,NaN,NaN,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077430,1314167.0,2500.0,30000.00,40876.0,1.00,0.0,36249.0,5.0,NaN,NaN,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077175,1313524.0,2400.0,12252.00,40876.0,8.72,0.0,37194.0,2.0,NaN,NaN,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1076863,1277178.0,10000.0,49200.00,40876.0,20.00,0.0,35094.0,1.0,35.0,NaN,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1075269,1311441.0,5000.0,36000.00,40876.0,11.20,0.0,38290.0,3.0,NaN,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069639,1304742.0,7000.0,47004.00,40876.0,23.51,0.0,38532.0,1.0,NaN,NaN,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1072053,1288686.0,3000.0,48000.00,40876.0,5.35,0.0,39081.0,2.0,NaN,NaN,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1071795,1306957.0,5600.0,40000.00,40876.0,5.55,0.0,38076.0,2.0,NaN,NaN,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1071570,1306721.0,5375.0,15000.00,40876.0,18.08,0.0,38229.0,0.0,NaN,NaN,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1070078,1305201.0,6500.0,72000.00,40876.0,16.12,0.0,35794.0,2.0,NaN,NaN,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069908,1305008.0,12000.0,75000.00,40876.0,10.78,0.0,32780.0,0.0,NaN,NaN,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1064687,1298717.0,9000.0,30000.00,40876.0,10.08,0.0,38076.0,1.0,NaN,NaN,4.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1069866,1304956.0,3000.0,15000.00,40876.0,12.56,0.0,37801.0,2.0,NaN,NaN,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069057,1303503.0,10000.0,100000.00,40876.0,7.06,0.0,33357.0,2.0,NaN,NaN,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069759,1304871.0,1000.0,28000.00,40876.0,20.31,0.0,39324.0,1.0,NaN,NaN,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1065775,1299699.0,10000.0,42000.00,40876.0,18.60,0.0,36067.0,2.0,61.0,NaN,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069971,1304884.0,3600.0,110000.00,40876.0,10.52,0.0,34180.0,0.0,NaN,NaN,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1062474,1294539.0,6000.0,84000.00,40876.0,18.44,2.0,37893.0,0.0,8.0,NaN,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1069742,1304855.0,9200.0,77385.19,40876.0,9.86,0.0,36890.0,0.0,NaN,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069740,1284848.0,20250.0,43370.00,40876.0,26.53,0.0,35733.0,3.0,NaN,NaN,8.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1039153,1269083.0,21000.0,105000.00,40876.0,13.22,0.0,30346.0,0.0,NaN,NaN,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069710,1304821.0,10000.0,50000.00,40876.0,11.18,0.0,31227.0,0.0,NaN,NaN,8.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069700,1304810.0,10000.0,50000.00,40876.0,16.01,0.0,37710.0,0.0,NaN,NaN,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069559,1304634.0,6000.0,76000.00,40876.0,2.40,0.0,37041.0,1.0,NaN,NaN,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069697,1273773.0,15000.0,92000.00,40876.0,29.44,0.0,37286.0,0.0,NaN,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069800,1304679.0,15000.0,60000.00,40876.0,15.22,0.0,37893.0,1.0,NaN,NaN,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069657,1304764.0,5000.0,50004.00,40876.0,13.97,3.0,37893.0,0.0,20.0,NaN,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069799,1304678.0,4000.0,106000.00,40876.0,5.63,1.0,30893.0,0.0,18.0,NaN,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1047704,1278806.0,8500.0,25000.00,40876.0,12.19,0.0,39020.0,0.0,NaN,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1032111,1261745.0,4375.0,17108.00,40876.0,20.34,0.0,32110.0,0.0,NaN,NaN,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37127712,39900482.0,5875.0,35000.00,42003.0,18.93,0.0,38959.0,1.0,NaN,119.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37217634,39990408.0,8000.0,36000.00,42003.0,6.60,0.0,38198.0,0.0,NaN,24.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37167534,39940303.0,35000.0,98000.00,42003.0,15.56,0.0,34971.0,1.0,29.0,NaN,31.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37137624,39910377.0,35000.0,120000.00,42003.0,31.21,0.0,31289.0,0.0,NaN,NaN,17.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
37317482,40080244.0,22000.0,104000.00,42003.0,7.93,0.0,35884.0,0.0,NaN,NaN,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37287488,40060242.0,3700.0,35000.00,42003.0,2.62,1.0,38290.0,1.0,19.0,NaN,8.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
37087435,39850186.0,12000.0,42000.00,42003.0,26.74,1.0,37133.0,0.0,11.0,NaN,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37077455,39840207.0,15600.0,42000.00,42003.0,16.71,0.0,37224.0,0.0,NaN,NaN,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37227443,40000189.0,2725.0,47784.00,42003.0,14.69,1.0,37224.0,1.0,11.0,44.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37167317,39940064.0,10000.0,32000.00,42003.0,11.40,0.0,40116.0,1.0,NaN,NaN,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37317288,40080027.0,10000.0,35000.00,42003.0,8.30,0.0,38928.0,3.0,28.0,NaN,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36799561,39552273.0,17025.0,108000.00,42003.0,12.47,0.0,36493.0,2.0,64.0,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
37077186,39839905.0,14000.0,69000.00,42003.0,8.23,0.0,37924.0,0.0,73.0,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37187152,39959868.0,15000.0,75000.00,42003.0,23.35,0.0,36190.0,0.0,NaN,NaN,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36200493,38911833.0,19600.0,49000.00,42003.0,22.58,1.0,32872.0,2.0,6.0,NaN,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36351602,39083061.0,18275.0,120000.00,42003.0,17.40,3.0,34423.0,2.0,7.0,NaN,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36808246,39560970.0,6000.0,42000.00,42003.0,10.66,0.0,31531.0,1.0,45.0,NaN,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37011266,39773999.0,28000.0,120000.00,42003.0,26.60,0.0,37893.0,0.0,69.0,NaN,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37041208,39803931.0,17000.0,63078.00,42003.0,31.70,0.0,36402.0,0.0,NaN,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36743377,39486112.0,4200.0,48000.00,42003.0,36.93,0.0,33084.0,0.0,38.0,NaN,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35773415,38468842.0,18700.0,52000.00,42003.0,11.28,0.0,37436.0,0.0,30.0,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35591131,38288343.0,25000.0,55000.00,42003.0,5.52,0.0,37740.0,0.0,NaN,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36231724,38943173.0,12000.0,40000.00,42003.0,25.65,1.0,38989.0,0.0,8.0,NaN,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36231718,38943165.0,10775.0,54000.00,42003.0,13.22,1.0,27697.0,0.0,16.0,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36241316,38952731.0,6225.0,27000.00,42003.0,18.58,0.0,40573.0,1.0,NaN,NaN,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36250208,38961532.0,13150.0,30000.00,42003.0,1.00,0.0,34453.0,0.0,NaN,NaN,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36421485,39142898.0,4000.0,50000.00,42003.0,12.63,0.0,37498.0,0.0,NaN,84.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36260758,38972123.0,10850.0,32000.00,42003.0,29.44,0.0,37406.0,1.0,65.0,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36330911,39042282.0,12000.0,63000.00,42003.0,23.69,1.0,34849.0,0.0,9.0,NaN,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36490806,39222577.0,12000.0,64400.00,42003.0,27.19,1.0,37893.0,2.0,22.0,NaN,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df_X.to_pickle("./data/df_X.pkl")
df_y.to_pickle("./data/df_y.pkl")

In [4]:
df_X = pd.read_pickle("./data/df_X_imputed.pkl")
df_y = pd.read_pickle("./data/df_y.pkl")

In [5]:
df_X.head()

,,funded_amnt,funded_amnt_inv,annual_inc,issue_d,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,...,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY
id,member_id,,,,,,,,,,,,,,,,,,,,,
1077501,1296599.0,5000.0,4975.0,24000.0,40876.0,27.65,0.0,31046.0,1.0,46.2,87.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077430,1314167.0,2500.0,2500.0,30000.0,40876.0,1.00,0.0,36249.0,5.0,51.6,100.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077175,1313524.0,2400.0,2400.0,12252.0,40876.0,8.72,0.0,37194.0,2.0,33.6,66.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1076863,1277178.0,10000.0,10000.0,49200.0,40876.0,20.00,0.0,35094.0,1.0,35.0,93.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1075269,1311441.0,5000.0,5000.0,36000.0,40876.0,11.20,0.0,38290.0,3.0,36.2,83.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**!! We are deleting these columns based on the high number of nulls, but they seem like they may contain valuable information. Time since delinquency for example should be quite predictive of future defaults. Leaving these columns intact for the time being!!**

In [27]:
#df_X.addr_state_None.value_counts()
df_X.verification_status_None.value_counts()

0.0    391064
Name: verification_status_None, dtype: int64

### Data Visualization

**!!Including this section from Final_Project_MASTER!!**

### Data Exploration

**!!Including this section from Final_Project_MASTER!!**

In [7]:
print 'Default/Paid ratio: %.1f%%' % (np.mean(df_y)*100)

Default/Paid ratio: 19.4%

### Pre-processing

*Libraries*

In [ ]:
df_X = df_X.drop(["verification_status_None", "term_None", "application_type_None", "initial_list_status_None", "purpose_None", "emp_length_None", "home_ownership_None", "addr_state_None", "funded_amnt_inv", "num_actv_rev_tl", "tot_cur_bal"], axis=1)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sclr = StandardScaler()
X = sclr.fit_transform(df_X)
y = df_y.values

In [35]:
X

array([[-1.08050166, -0.79521509, -1.33900391, ..., -0.11207331,
        -0.06742916, -0.04879782],
       [-1.38461029, -0.69857784, -1.33900391, ..., -0.11207331,
        -0.06742916, -0.04879782],
       [-1.39677464, -0.98443082, -1.33900391, ..., -0.11207331,
        -0.06742916, -0.04879782],
       ...,
       [-0.36888746, -0.66636543,  0.88492921, ..., -0.11207331,
        -0.06742916, -0.04879782],
       [-0.22899749, -0.16707298,  0.88492921, ..., -0.11207331,
        -0.06742916, -0.04879782],
       [-0.22899749, -0.14452429,  0.88492921, ..., -0.11207331,
        -0.06742916, -0.04879782]])

In [37]:
def custom_cost(y, y_pred):
    cost_fixed_application = 10.0
    cost_fixed_servicing = 100.0
    cost_default = 15000.0
    cost_interest = -1000.0
    
    # TRUE POSITIVE: Predict default, applicant would default
    n_true_positive = sum((y==1) & (y_pred==1))
    # We only pay fixed application processing costs as we decline the loan
    cost_true_positive = n_true_positive*(cost_fixed_application)
    
    # TRUE NEGATIVE: Predict pay on time, applicant will pay on time
    n_true_negative = sum((y==0) & (y_pred==0))
    # We pay fixed application processing costs, costs of servicing the loan, and gain profit on interest payments
    cost_true_negative = n_true_negative*(cost_fixed_application + cost_fixed_servicing + cost_interest)
    
    # FALSE POSITIVE: Predict default, applicant would pay on time
    n_false_positive = sum((y==0) & (y_pred==1))
    # We only pay fixed application processing costs as we decline the loan
    cost_false_positive = n_false_positive*(cost_fixed_application)
    
    # FALSE NEGATIVE: Predict pay on time, applicant will default
    n_false_negative = sum((y==1) & (y_pred==0))
    # We pay fixed application processing costs, costs of servicing the loan, and the principal as the loan defaults
    cost_false_negative = n_false_negative*(cost_fixed_application + cost_fixed_servicing + cost_default)
    
    return (cost_true_positive + cost_true_negative + cost_false_positive + cost_false_negative)/len(y)

In [40]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20161201)

In [74]:
def test_model(model, scoring_funcs):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
        
    scores = {"model": eval(model)}
    for scoring_func in scoring_funcs:
        scores[scoring_func.__name__] = scoring_func(y_test, y_pred)
    
    return pd.DataFrame([scores]).set_index("model")

def compare_models(models, labels, scoring_funcs):
    return pd.concat([test_model(model, scoring_funcs) for model in zip(models, labels)])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score

from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.tree import DecisionTreeClassifier as DecisionTree
from sklearn.ensemble import RandomForestClassifier as RandomForest
from sklearn.svm import SVC

lda__None__None = LDA()

compare_models([lda, qda, knn], ["LDA", "QDA", "KNN"], [custom_cost, accuracy_score, average_precision_score, f1_score, log_loss, precision_score, recall_score, roc_auc_score])

In [ ]:
dtree = DecisionTree()
rf = RandomForest()
svc = SVC()

compare_models([dtree, rf, svc], ["DTree", "RForest", "SVC"], [custom_cost, accuracy_score, average_precision_score, f1_score, log_loss, precision_score, recall_score, roc_auc_score])