<br>
<br>
**<font size=5><center>Predicting Default Rates for Lending Club</center></font>**

### Authors:

<font size=5>Devon Luongo</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>deluongo@gmail.com</font> <br>

<font size=5>Ben Yuen</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>benyuen@hotmail.com</font> <br>

<font size=5>Bryn Clarke</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3></font>clarke.bryn@gmail.com<br>

<font size=5>Ankit Agarwal</font> <br>
<font size=4>Harvard University</font> <br>
<font size=3>ankit.frnz@gmail.com</font> <br>

**<font size=4><center>Abstract</center></font>**

<center>**!!(Insert Abstract)!!**</center>

# I. Introduction

Lending Club is an online marketplace that fascilitates the lending money to individuals or businesses through online services that match lenders directly with borrowers. This practice is called Peer-to-Peer (P2P) Lending. With an A+ BBB rating, Lending Club offers an attractive alternative to bonds for steady investment income. Lending Club also states that borrowers are able to reduce their loans by an average of 30%.

"Since peer-to-peer lending companies offering these services operate entirely online, they can run with lower overhead and provide the service more cheaply than traditional financial institutions. As a result, lenders often earn higher returns compared to savings and investment products offered by banks, while borrowers can borrow money at lower interest rates, even after the P2P lending company has taken a fee for providing the match-making platform and credit checking the borrower."

The downside to Lending Club however, is that most peer-to-peer loans are unsecured personal loans, meaning lenders incur a higher risk than comparable steady income investments like Treasury Bonds. Therefore, the investment quality of each loan depends largly on three factors: the expected return, the level of risk aversion, and the risk incurred. The first factor is built into the contract of the loan, and the second factor is personal preference. Therefore, the primary variable that that investors must identify when compoaring P2P Lending with other investment opportunities is the default risk for each loan. 

For this reason, Lending Club offers lenders a dataset containing a comprehensive list of features that can be employed to make better lending decisions. Detailed information for every loan have been issued by Lending Club from 2007 to 2015. Among**!!(Insert Num Predictors)!!** features or predictors in total, the dataset includes a borrowerâ€™s annual incomes, zip codes, revolving balances, and purpose for borrowing.

Our objective was to build on similar projects conducted in recent years to construct a model for default risk to help lenders decrease the risk they occur when lending. We trained and tested a range of models in an attempt to identify the best performing model. Additionally, we constructed a cost based model aimed at maximizing Lending Clubs overhead.

# II. Related Work

**!!(Rewrite After Models Complete)!!** 
Prior projects like **!!("Predicting borrowers chance of defaulting on credit loans" [1])!!** have set great examples of applying machine learning to improve loan default prediction in a Kaggle competition, and authors for**!!("Predicting Probability of Loan Default" [2])!!**  have shown that Random Forest appeared to be the best performing model on the Kaggle data. 

However, despite the early success using Random Forest for default prediction, real-world records often behaves differently from curated data, and a later study **!!("Peer Lending Risk Predictor" [3])!!** presented that a modified Logistic Regression model could outperform SVM, Naive Bayes, and even Random Forest on Lending Club data. 

The fact that Logistic Regression performance could be immensely improved by simply adding penalty factor on misclassification gave rise to our interest in fine tuning other not-yet optimized models, in particular, SVM and Naive Bayes, to continue the search for a better predictive model in the realm of loan default. Besides the difference in types of model that they focus on, the prior studies only used the out-of-the-box dataset from Kaggle or
Lending Club, but research like **!!("The sensitivity of the loss given default rate to systematic risk" [4])!!** has shown the linkage between default rate and macroeconomic factors, so we have decided to add in census data, with info like regional median income, to train our models on a more holistic set of features.

# III. Data

### Data Preparation

*Libraries*

In [1]:
import pandas as pd
import numpy as np

Some of the data files have fields that contain NAs for older time periods. In order to collapse the data sets into one file, all numerical data will be stored in float fields (integer fields do not support NA missing values). To do this, we first define a conversion dictionary that stores the numeric fields with lookups to the *float* data type.

In [2]:
convert_float = dict([s, float] for s in
                     ['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'installment',
                      'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'mths_since_last_delinq',                      
                      'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
                      'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
                      'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
                      'last_pymnt_amnt', 'collections_12_mths_ex_med', 'mths_since_last_major_derog',
                      'annual_inc_joint', 'dti_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 
                      'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 
                      'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 
                      'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 
                      'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
                      'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
                      'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc',
                      'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq',
                      'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 
                      'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
                      'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
                      'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
                      'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
                      'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'])

We also define a dictionary of string fields, to handle situations where the inferred data type might be numeric even though the field should be read in as a string/object.

In [3]:
convert_str = dict([s, str] for s in
                    ['term', 'int_rate', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 
                     'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 
                     'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util', 
                     'initial_list_status', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d',
                     'policy_code', 'application_type', 'verification_status_joint'])

We also define a dictionary of string fields, to handle situations where the inferred data type might be numeric even though the field should be read in as a string/object.

In [4]:
convert_categ = dict([s, "categorical"] for s in
                      ["term", "grade", "sub_grade", "home_ownership", "emp_length",
                       "verification_status", "loan_status", "pymnt_plan", "purpose", "addr_state",
                       "initial_list_status", "policy_code", "application_type", "verification_status_joint"])

We read the input data from the CSV data files using pandas *read_csv*. There is a blank row in the data header and there are two blank rows in the footer of each file. To allow the use of *skip_footer*, we use the python engine rather than the C engine. The first two columns (*id* and *member_id*) are unique and used to create a table index.

In [5]:
def read_data(file_loc):
    data = pd.read_csv(file_loc,
                       skiprows=1,
                       skip_footer=2,
                       engine="python",
                       na_values=['NaN', 'nan'],
                       converters=convert_str,
                       index_col=[0,1])
    
    # Depending on the specific dataset used, the numeric values may be read in as integers.
    # For best performance and to enable mergining of the datasets, we convert those fields
    # to floats (which allow NaN values):
    for k, v in convert_float.items():
        data[k] = data[k].astype(v)
    
    # There are 5 object fields that contain dates in the format *YYYY-MMM* (e.g. '2010-Jan').
    # We parse those to return datetime fields, which are more easily input into time series models
    # or plotted in charts.
    data.issue_d = pd.to_datetime(data.issue_d, errors="coerce")
    data.last_pymnt_d = pd.to_datetime(data.last_pymnt_d, errors="coerce")
    data.next_pymnt_d = pd.to_datetime(data.next_pymnt_d, errors="coerce")
    data.last_credit_pull_d = pd.to_datetime(data.last_credit_pull_d, errors="coerce")
    data.earliest_cr_line = pd.to_datetime(data.earliest_cr_line, errors="coerce")
    
    return data

data = pd.concat([read_data(s) for s in ["./data/LoanStats3a.csv", "./data/LoanStats3b.csv", "./data/LoanStats3c.csv", "./data/LoanStats3d.csv"]])

In [6]:
print data.shape

(887441, 109)

Many of the remaining fields contain categorical data. We use the pandas *category* data type to store the data more efficiently.

In [7]:
for k, v in convert_categ.items():
    data[k] = pd.Categorical(data[k])

Some percentages are stored as strings (*int_rate*, *revol_util*). Here we convert them into a float by stripping the % symbol and dividing by 100.

In [8]:
def percent_to_float(s):
    if (type(s) == str):
        if ("%" in s):
            return float(str(s).strip("%"))/100
        else:
            if s == "None":
                return np.nan
            else:            
                return s
    else:
        return s

data.int_rate = [percent_to_float(s) for s in data.int_rate]
data.revol_util = [percent_to_float(s) for s in data.revol_util]

In [9]:
# The remaining 5 object type fields are dropped as they aren't easily incorporated in a design matrix
data = data.drop(["emp_title", "url", "desc", "title", "zip_code"], axis=1)

In [10]:
# We decided to convert the date fields to the number of days since 1/1/1900
for date_col in ["issue_d", "earliest_cr_line", "last_pymnt_d", "next_pymnt_d", "last_credit_pull_d"]:
    data.loc[:, date_col] = (data.loc[:, date_col] - pd.to_datetime("1/1/1900")).dt.days

In [11]:
# Let us see what status we have.
print data["loan_status"].value_counts()

Current                                                467679
Fully Paid                                             315192
Charged Off                                             75740
Late (31-120 days)                                      14548
In Grace Period                                          8432
Late (16-30 days)                                        2968
Does not meet the credit policy. Status:Fully Paid       1988
Does not meet the credit policy. Status:Charged Off       761
Default                                                   132
None                                                        1
Name: loan_status, dtype: int64

In [12]:
# Ok we dont want current or None status as we don't know what is going to happen with those.
# next also late and grace period we are not sure about.
# thirdly we remove loans that do not meet credit policy so we can convert our issue to a binar model
data = data[((data["loan_status"] == "Default") | (data["loan_status"] == "Charged Off") | (data["loan_status"] == "Fully Paid"))]

# Rename "Charged off to default"
data["loan_status"] = data["loan_status"].replace("Charged Off", "Default")
data["loan_status"] = data["loan_status"].replace("Default", 1)
data["loan_status"] = data["loan_status"].replace("Fully Paid", 0)
print data.shape
print data["loan_status"].value_counts()

(391064, 104)
0    315192
1     75872
Name: loan_status, dtype: int64

In [13]:
# There are only 50 joint applications, so we coalesce the fields that have joint values (annual_inc, dti, verification_status)
for joint_col in ["annual_inc", "dti", "verification_status"]:
    data.loc[data.application_type=="Joint", joint_col] = data.loc[data.application_type=="Joint", joint_col + "_joint"]

data = data.drop(["annual_inc_joint", "dti_joint", "verification_status_joint"], axis=1)

In [14]:
# policy_code has only one level, "1", and pymnt_plan is all "N" except for 4 records so we drop both 
data = data.drop(["pymnt_plan", "policy_code"], axis=1)

In [15]:
# While grade and sub_grade are thought to be predictive, they use Lending Tree's credit model and we don't
# want to influence our scoring model using their model that will capture much of the same information
# This is also true of int_rate and installment, which are each correlated with LT's credit grade
data = data.drop(["int_rate", "installment", "grade", "sub_grade"], axis=1)

In [16]:
# Finally we drop other fields that are not known a priori and may contain information
# post-default / delinquency that will bias our results
# This includes payment history and loan balances
data = data.drop(["out_prncp", "out_prncp_inv", "total_pymnt", "total_pymnt_inv", "total_rec_prncp",
                  "total_rec_int", "total_rec_late_fee", "recoveries", "collection_recovery_fee",
                  "last_pymnt_d", "last_pymnt_amnt", "next_pymnt_d", "last_credit_pull_d"], axis=1)

In [45]:
print "Pearson correlation between [%s] and [%s]: %.3f" % ("funded_amnt", "funded_amnt_inv", np.corrcoef(data.funded_amnt, data.funded_amnt_inv)[0,1])

Pearson correlation between [funded_amnt] and [funded_amnt_inv]: 0.997

In [ ]:
# There is nearly perfect correlation between funded_amnt and funded_amnt_inv, so we remove funded_amnt_inv
data = data.drop(["funded_amnt_inv"], axis=1)

In [17]:
#import quandl
state_list = ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL",
              "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA",
              "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE",
              "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI",
              "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV",
              "WY"]
#state_unemployment_data = {}
#for i in state_list:
#    try:
#        print(i)
#        result = quandl.get('FRED/{:s}UR'.format(i))
#        state_unemployment_data[i] = result
#    except RuntimeError as e:
#        print(e)

#check all indices are sorted by date
#for s in state_unemployment_data.keys():
#    if not state_unemployment_data[s].index.is_monotonic:
#        print s

#convert percentages to a value in the range [0, 1]
#for s in state_unemployment_data.keys():
#    state_unemployment_data[s]['VALUE'] = state_unemployment_data[s]['VALUE'] / 100.0

#import pickle
#with open('unemployment_rates_by_state.pkl', 'wb') as f:
#    pickle.dump(state_unemployment_data, f)

In [18]:
import pickle
with open('unemployment_rates_by_state.pkl', 'rb') as f:
    state_unemployment_data = pickle.load(f)

In [19]:
def get_state_unemp_df(s):
    unemp_data = state_unemployment_data[s]
    unemp_data = unemp_data.rename(columns={'VALUE':s})
    return unemp_data

df_unemp = pd.concat([get_state_unemp_df(s) for s in state_list], axis=1)
df_unemp.index = (pd.to_datetime(df_unemp.index) - pd.to_datetime("1/1/1900")).days

In [20]:
def lookup_unemp(issue_date, state):
    try:
        result = df_unemp.loc[issue_date, state]
    except:
        result = np.na
    return result

data.state_unemp_rate = [lookup_unemp(issue_date, state) for issue_date, state in zip(data.issue_d, data.addr_state)]

In [21]:
df_y = data["loan_status"]
df_X = data.drop("loan_status", axis=1)
# Remove member id.
df_X = df_X.ix[:, 1:]

In [22]:
print df_X.shape
print df_y.shape

(391064, 80)
(391064,)

In [23]:
for k, v in convert_categ.items():
    if not(k in ["verification_status_joint", "policy_code", "grade", "sub_grade", "pymnt_plan", "loan_status"]):
        df_X = pd.concat([df_X,
                          pd.get_dummies(df_X[k], prefix=k)],
                         axis=1)
        df_X = df_X.drop(k, axis=1)

In [24]:
df_X

,,funded_amnt,funded_amnt_inv,annual_inc,issue_d,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,...,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY
id,member_id,,,,,,,,,,,,,,,,,,,,,
1077501,1296599.0,5000.0,4975.000000,24000.00,40876.0,27.65,0.0,31046.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077430,1314167.0,2500.0,2500.000000,30000.00,40876.0,1.00,0.0,36249.0,5.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1077175,1313524.0,2400.0,2400.000000,12252.00,40876.0,8.72,0.0,37194.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1076863,1277178.0,10000.0,10000.000000,49200.00,40876.0,20.00,0.0,35094.0,1.0,35.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1075269,1311441.0,5000.0,5000.000000,36000.00,40876.0,11.20,0.0,38290.0,3.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069639,1304742.0,7000.0,7000.000000,47004.00,40876.0,23.51,0.0,38532.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1072053,1288686.0,3000.0,3000.000000,48000.00,40876.0,5.35,0.0,39081.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1071795,1306957.0,5600.0,5600.000000,40000.00,40876.0,5.55,0.0,38076.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1071570,1306721.0,5375.0,5350.000000,15000.00,40876.0,18.08,0.0,38229.0,0.0,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1070078,1305201.0,6500.0,6500.000000,72000.00,40876.0,16.12,0.0,35794.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069908,1305008.0,12000.0,12000.000000,75000.00,40876.0,10.78,0.0,32780.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1064687,1298717.0,9000.0,9000.000000,30000.00,40876.0,10.08,0.0,38076.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1069866,1304956.0,3000.0,3000.000000,15000.00,40876.0,12.56,0.0,37801.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069057,1303503.0,10000.0,10000.000000,100000.00,40876.0,7.06,0.0,33357.0,2.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069759,1304871.0,1000.0,1000.000000,28000.00,40876.0,20.31,0.0,39324.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1065775,1299699.0,10000.0,10000.000000,42000.00,40876.0,18.60,0.0,36067.0,2.0,61.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069971,1304884.0,3600.0,3600.000000,110000.00,40876.0,10.52,0.0,34180.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1062474,1294539.0,6000.0,6000.000000,84000.00,40876.0,18.44,2.0,37893.0,0.0,8.0,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1069742,1304855.0,9200.0,9200.000000,77385.19,40876.0,9.86,0.0,36890.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069740,1284848.0,20250.0,19142.161077,43370.00,40876.0,26.53,0.0,35733.0,3.0,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1039153,1269083.0,21000.0,21000.000000,105000.00,40876.0,13.22,0.0,30346.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069710,1304821.0,10000.0,10000.000000,50000.00,40876.0,11.18,0.0,31227.0,0.0,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069700,1304810.0,10000.0,10000.000000,50000.00,40876.0,16.01,0.0,37710.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069559,1304634.0,6000.0,6000.000000,76000.00,40876.0,2.40,0.0,37041.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069697,1273773.0,15000.0,15000.000000,92000.00,40876.0,29.44,0.0,37286.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069800,1304679.0,15000.0,8725.000000,60000.00,40876.0,15.22,0.0,37893.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069657,1304764.0,5000.0,5000.000000,50004.00,40876.0,13.97,3.0,37893.0,0.0,20.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069799,1304678.0,4000.0,4000.000000,106000.00,40876.0,5.63,1.0,30893.0,0.0,18.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1047704,1278806.0,8500.0,8500.000000,25000.00,40876.0,12.19,0.0,39020.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1032111,1261745.0,4375.0,4375.000000,17108.00,40876.0,20.34,0.0,32110.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37127712,39900482.0,5875.0,5875.000000,35000.00,42003.0,18.93,0.0,38959.0,1.0,NaN,119.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37217634,39990408.0,8000.0,8000.000000,36000.00,42003.0,6.60,0.0,38198.0,0.0,NaN,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37167534,39940303.0,35000.0,35000.000000,98000.00,42003.0,15.56,0.0,34971.0,1.0,29.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37137624,39910377.0,35000.0,35000.000000,120000.00,42003.0,31.21,0.0,31289.0,0.0,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
37317482,40080244.0,22000.0,21975.000000,104000.00,42003.0,7.93,0.0,35884.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37287488,40060242.0,3700.0,3700.000000,35000.00,42003.0,2.62,1.0,38290.0,1.0,19.0,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
37087435,39850186.0,12000.0,12000.000000,42000.00,42003.0,26.74,1.0,37133.0,0.0,11.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37077455,39840207.0,15600.0,15600.000000,42000.00,42003.0,16.71,0.0,37224.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37227443,40000189.0,2725.0,2725.000000,47784.00,42003.0,14.69,1.0,37224.0,1.0,11.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37167317,39940064.0,10000.0,10000.000000,32000.00,42003.0,11.40,0.0,40116.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37317288,40080027.0,10000.0,10000.000000,35000.00,42003.0,8.30,0.0,38928.0,3.0,28.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36799561,39552273.0,17025.0,17025.000000,108000.00,42003.0,12.47,0.0,36493.0,2.0,64.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
37077186,39839905.0,14000.0,14000.000000,69000.00,42003.0,8.23,0.0,37924.0,0.0,73.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37187152,39959868.0,15000.0,15000.000000,75000.00,42003.0,23.35,0.0,36190.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36200493,38911833.0,19600.0,19600.000000,49000.00,42003.0,22.58,1.0,32872.0,2.0,6.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36351602,39083061.0,18275.0,18275.000000,120000.00,42003.0,17.40,3.0,34423.0,2.0,7.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36808246,39560970.0,6000.0,6000.000000,42000.00,42003.0,10.66,0.0,31531.0,1.0,45.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37011266,39773999.0,28000.0,28000.000000,120000.00,42003.0,26.60,0.0,37893.0,0.0,69.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37041208,39803931.0,17000.0,17000.000000,63078.00,42003.0,31.70,0.0,36402.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36743377,39486112.0,4200.0,4200.000000,48000.00,42003.0,36.93,0.0,33084.0,0.0,38.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35773415,38468842.0,18700.0,18700.000000,52000.00,42003.0,11.28,0.0,37436.0,0.0,30.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35591131,38288343.0,25000.0,25000.000000,55000.00,42003.0,5.52,0.0,37740.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36231724,38943173.0,12000.0,12000.000000,40000.00,42003.0,25.65,1.0,38989.0,0.0,8.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36231718,38943165.0,10775.0,10775.000000,54000.00,42003.0,13.22,1.0,27697.0,0.0,16.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36241316,38952731.0,6225.0,6225.000000,27000.00,42003.0,18.58,0.0,40573.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36250208,38961532.0,13150.0,13150.000000,30000.00,42003.0,1.00,0.0,34453.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36421485,39142898.0,4000.0,4000.000000,50000.00,42003.0,12.63,0.0,37498.0,0.0,NaN,84.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36260758,38972123.0,10850.0,10850.000000,32000.00,42003.0,29.44,0.0,37406.0,1.0,65.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36330911,39042282.0,12000.0,12000.000000,63000.00,42003.0,23.69,1.0,34849.0,0.0,9.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36490806,39222577.0,12000.0,12000.000000,64400.00,42003.0,27.19,1.0,37893.0,2.0,22.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df_X.to_pickle("./data/df_X.pkl")
df_y.to_pickle("./data/df_y.pkl")

**!! We are deleting these columns based on the high number of nulls, but they seem like they may contain valuable information. Time since delinquency for example should be quite predictive of future defaults. Leaving these columns intact for the time being!!**

In [26]:
# There is only so much we can do, delete features that have more than 40% 
# of data as nan.
for col in df_X.columns:
    if (df_X[col].isnull().sum()/float(df_X.shape[0])) > 0.4:
        #df_X = df_X.drop(col, axis=1)
        print col
#print df_X.shape

mths_since_last_delinq
mths_since_last_record
mths_since_last_major_derog
open_acc_6m
open_il_6m
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
inq_fi
total_cu_tl
inq_last_12m
mths_since_recent_bc_dlq
mths_since_recent_revol_delinq

### Data Visualization

**!!Including this section from Final_Project_MASTER!!**

### Data Exploration

**!!Including this section from Final_Project_MASTER!!**

In [27]:
print 'Default/Paid ratio: %.1f%%' % (np.mean(df_y)*100)

Default/Paid ratio: 19.4%

### Pre-processing

*Libraries*

In [28]:
from sklearn.preprocessing import Imputer
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import ExtraTreesClassifier

In [29]:
# Split into training and test data
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.3, random_state=20161201)

In [30]:
def impute_mean(X_train, X_test):
    imp = Imputer(missing_values='NaN', strategy='mean', axis=0, copy=True)
    imp.fit(X_train)
    return imp.transform(X_train), imp.transform(X_test)

def impute_knn(X_train, X_test):
    # NOT IMPLEMENTED
    knn = NearestNeighbors(n_neighbors=5)
    knn.fit(X_train)
    return knn.predict(X_train), knn.predict(X_test)

X_train, X_test = impute_mean(df_X_train, df_X_test)

In [31]:
def scale_std(X_train, X_test, n_col):
    sclr = StandardScaler()
    sclr.fit(X_train)
    X_train_sc = sclr.transform(X_train)
    X_test_sc = sclr.transform(X_test)
    X_train_sc[:, n_col:] = X_train[:, n_col:]
    X_test_sc[:, n_col:] = X_test[:, n_col:]
    return X_train_sc, X_test_sc

# Only scale the first 74 columns (the remaining columns are one-hot encoded)
X_train, X_test = scale_std(X_train, X_test, 74)

In [32]:
df_X_train_pp = pd.DataFrame(X_train, index=df_X_train.index, columns=df_X_train.columns)
df_X_test_pp = pd.DataFrame(X_test, index=df_X_test.index, columns=df_X_test.columns)

In [33]:
X_train = np.array(df_X_train_pp)
X_test = np.array(df_X_test_pp)
y_train = np.array(df_y_train)
y_test = np.array(df_y_test)
np.save("./data/X_train.npy", X_train)
np.save("./data/X_test.npy", X_test)
np.save("./data/y_train.npy", y_train)
np.save("./data/y_test.npy", y_test)

### Feature Selection

*Libraries*

In [34]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [36]:
def feature_plot(X, y, estimators, features_to_print):
    # Build a forest and compute the feature importances
    forest = ExtraTreesClassifier(n_estimators=estimators,
                                  random_state=0)

    forest.fit(X, y)
    importances = forest.feature_importances_
    std = np.std([tree.feature_importances_ for tree in forest.estimators_],
                 axis=0)
    indices = np.argsort(importances)[::-1]

    # Print the feature ranking
    print("Feature ranking:")

    for f in range(features_to_print):
        print("%d. feature %d (%f) %s" % (f + 1, indices[f], importances[indices[f]], X.columns[indices[f]]))
    
    for f in range(features_to_print):
        print '"' + str(X.columns[f]) + '",'
    
    # Plot the feature importances of the forest
    plt.figure()
    plt.title("Feature importances")
    indices = indices[0:features_to_print]
    plt.bar(range(features_to_print), importances[indices],
           color="r", yerr=std[indices], align="center")
    plt.xticks(range(features_to_print), indices)
    plt.xlim([-1, range(features_to_print)])
    plt.show()

# We ran this test on multiple small subsets of data and got similar results.
feature_plot(df_X_train_pp, df_y_train, 1, 172)

Feature ranking:
1. feature 4 (0.026873) dti
2. feature 3 (0.023185) issue_d
3. feature 77 (0.020368) term_ 60 months
4. feature 13 (0.020214) revol_util
5. feature 1 (0.019958) funded_amnt_inv
6. feature 2 (0.019616) annual_inc
7. feature 0 (0.019259) funded_amnt
8. feature 14 (0.018642) total_acc
9. feature 6 (0.018155) earliest_cr_line
10. feature 10 (0.017541) open_acc
11. feature 12 (0.017338) revol_bal
12. feature 7 (0.016769) inq_last_6mths
13. feature 38 (0.015896) bc_util
14. feature 8 (0.014989) mths_since_last_delinq
15. feature 35 (0.014928) acc_open_past_24mths
16. feature 70 (0.014864) total_bc_limit
17. feature 65 (0.014701) percent_bc_gt_75
18. feature 42 (0.014318) mo_sin_old_rev_tl_op
19. feature 37 (0.013910) bc_open_to_buy
20. feature 46 (0.013874) mths_since_recent_bc
21. feature 53 (0.013809) num_bc_sats
22. feature 48 (0.013727) mths_since_recent_inq
23. feature 54 (0.013706) num_bc_tl
24. feature 63 (0.013647) num_tl_op_past_12m
25. feature 36 (0.013613) avg_cur_bal
26. feature 41 (0.013480) mo_sin_old_il_acct
27. feature 69 (0.013306) total_bal_ex_mort
28. feature 68 (0.013304) tot_hi_cred_lim
29. feature 31 (0.013104) total_rev_hi_lim
30. feature 57 (0.013064) num_rev_accts
31. feature 58 (0.013059) num_rev_tl_bal_gt_0
32. feature 44 (0.012693) mo_sin_rcnt_tl
33. feature 52 (0.012683) num_actv_rev_tl
34. feature 43 (0.012649) mo_sin_rcnt_rev_tl_op
35. feature 59 (0.012645) num_sats
36. feature 51 (0.012583) num_actv_bc_tl
37. feature 55 (0.012430) num_il_tl
38. feature 19 (0.012422) tot_cur_bal
39. feature 56 (0.012198) num_op_rev_tl
40. feature 71 (0.011805) total_il_high_credit_limit
41. feature 45 (0.011702) mort_acc
42. feature 64 (0.011016) pct_tl_nvr_dlq
43. feature 49 (0.009657) mths_since_recent_revol_delinq
44. feature 101 (0.009314) emp_length_10+ years
45. feature 47 (0.009115) mths_since_recent_bc_dlq
46. feature 88 (0.009072) purpose_debt_consolidation
47. feature 16 (0.008926) mths_since_last_major_derog
48. feature 76 (0.008850) term_ 36 months
49. feature 75 (0.008562) verification_status_Verified
50. feature 50 (0.008486) num_accts_ever_120_pd
51. feature 5 (0.008026) delinq_2yrs
52. feature 124 (0.007662) addr_state_CA
53. feature 74 (0.007337) verification_status_Source Verified
54. feature 9 (0.007333) mths_since_last_record
55. feature 87 (0.007159) purpose_credit_card
56. feature 18 (0.006977) tot_coll_amt
57. feature 73 (0.006643) verification_status_Not Verified
58. feature 11 (0.006623) pub_rec
59. feature 129 (0.006537) addr_state_FL
60. feature 102 (0.006253) emp_length_2 years
61. feature 154 (0.006100) addr_state_NY
62. feature 103 (0.006025) emp_length_3 years
63. feature 83 (0.005685) initial_list_status_f
64. feature 114 (0.005655) home_ownership_MORTGAGE
65. feature 66 (0.005650) pub_rec_bankruptcies
66. feature 110 (0.005553) emp_length_< 1 year
67. feature 105 (0.005509) emp_length_5 years
68. feature 84 (0.005392) initial_list_status_w
69. feature 100 (0.005278) emp_length_1 year
70. feature 104 (0.005244) emp_length_4 years
71. feature 106 (0.004948) emp_length_6 years
72. feature 119 (0.004944) home_ownership_RENT
73. feature 107 (0.004898) emp_length_7 years
74. feature 151 (0.004661) addr_state_NJ
75. feature 112 (0.004603) emp_length_n/a
76. feature 95 (0.004586) purpose_other
77. feature 108 (0.004425) emp_length_8 years
78. feature 109 (0.004073) emp_length_9 years
79. feature 134 (0.004003) addr_state_IL
80. feature 156 (0.003932) addr_state_OH
81. feature 130 (0.003917) addr_state_GA
82. feature 159 (0.003871) addr_state_PA
83. feature 118 (0.003837) home_ownership_OWN
84. feature 62 (0.003794) num_tl_90g_dpd_24m
85. feature 90 (0.003726) purpose_home_improvement
86. feature 142 (0.003643) addr_state_MI
87. feature 147 (0.003550) addr_state_NC
88. feature 166 (0.003418) addr_state_VA
89. feature 139 (0.003402) addr_state_MA
90. feature 168 (0.003315) addr_state_WA
91. feature 60 (0.003181) num_tl_120dpd_2m
92. feature 140 (0.003149) addr_state_MD
93. feature 123 (0.003099) addr_state_AZ
94. feature 97 (0.003046) purpose_small_business
95. feature 153 (0.002777) addr_state_NV
96. feature 125 (0.002766) addr_state_CO
97. feature 143 (0.002698) addr_state_MN
98. feature 67 (0.002623) tax_liens
99. feature 144 (0.002568) addr_state_MO
100. feature 92 (0.002452) purpose_major_purchase
101. feature 135 (0.002404) addr_state_IN
102. feature 169 (0.002308) addr_state_WI
103. feature 121 (0.002305) addr_state_AL
104. feature 126 (0.002281) addr_state_CT
105. feature 138 (0.002246) addr_state_LA
106. feature 163 (0.002158) addr_state_TN
107. feature 158 (0.002135) addr_state_OR
108. feature 15 (0.001890) collections_12_mths_ex_med
109. feature 137 (0.001779) addr_state_KY
110. feature 157 (0.001756) addr_state_OK
111. feature 161 (0.001755) addr_state_SC
112. feature 122 (0.001741) addr_state_AR
113. feature 93 (0.001650) purpose_medical
114. feature 61 (0.001604) num_tl_30dpd
115. feature 94 (0.001545) purpose_moving
116. feature 152 (0.001524) addr_state_NM
117. feature 86 (0.001507) purpose_car
118. feature 165 (0.001492) addr_state_UT
119. feature 136 (0.001464) addr_state_KS
120. feature 98 (0.001179) purpose_vacation
121. feature 131 (0.001154) addr_state_HI
122. feature 170 (0.000966) addr_state_WV
123. feature 39 (0.000956) chargeoff_within_12_mths
124. feature 91 (0.000944) purpose_house
125. feature 160 (0.000898) addr_state_RI
126. feature 164 (0.000820) addr_state_TX
127. feature 145 (0.000760) addr_state_MS
128. feature 99 (0.000723) purpose_wedding
129. feature 162 (0.000691) addr_state_SD
130. feature 150 (0.000666) addr_state_NH
131. feature 127 (0.000617) addr_state_DC
132. feature 128 (0.000602) addr_state_DE
133. feature 120 (0.000594) addr_state_AK
134. feature 146 (0.000546) addr_state_MT
135. feature 40 (0.000539) delinq_amnt
136. feature 17 (0.000488) acc_now_delinq
137. feature 171 (0.000476) addr_state_WY
138. feature 167 (0.000378) addr_state_VT
139. feature 27 (0.000325) open_rv_12m
140. feature 26 (0.000289) il_util
141. feature 96 (0.000285) purpose_renewable_energy
142. feature 20 (0.000249) open_acc_6m
143. feature 34 (0.000242) inq_last_12m
144. feature 21 (0.000238) open_il_6m
145. feature 28 (0.000220) open_rv_24m
146. feature 23 (0.000207) open_il_24m
147. feature 30 (0.000190) all_util
148. feature 32 (0.000190) inq_fi
149. feature 29 (0.000189) max_bal_bc
150. feature 33 (0.000189) total_cu_tl
151. feature 149 (0.000175) addr_state_NE
152. feature 22 (0.000174) open_il_12m
153. feature 24 (0.000173) mths_since_rcnt_il
154. feature 25 (0.000148) total_bal_il
155. feature 117 (0.000116) home_ownership_OTHER
156. feature 89 (0.000103) purpose_educational
157. feature 80 (0.000067) application_type_JOINT
158. feature 115 (0.000047) home_ownership_NONE
159. feature 148 (0.000032) addr_state_ND
160. feature 133 (0.000019) addr_state_ID
161. feature 141 (0.000012) addr_state_ME
162. feature 79 (0.000012) application_type_INDIVIDUAL
163. feature 82 (0.000000) initial_list_status_None
164. feature 81 (0.000000) application_type_None
165. feature 111 (0.000000) emp_length_None
166. feature 113 (0.000000) home_ownership_ANY
167. feature 116 (0.000000) home_ownership_None
168. feature 132 (0.000000) addr_state_IA
169. feature 78 (0.000000) term_None
170. feature 155 (0.000000) addr_state_None
171. feature 72 (0.000000) verification_status_None
172. feature 85 (0.000000) purpose_None
"funded_amnt",
"funded_amnt_inv",
"annual_inc",
"issue_d",
"dti",
"delinq_2yrs",
"earliest_cr_line",
"inq_last_6mths",
"mths_since_last_delinq",
"mths_since_last_record",
"open_acc",
"pub_rec",
"revol_bal",
"revol_util",
"total_acc",
"collections_12_mths_ex_med",
"mths_since_last_major_derog",
"acc_now_delinq",
"tot_coll_amt",
"tot_cur_bal",
"open_acc_6m",
"open_il_6m",
"open_il_12m",
"open_il_24m",
"mths_since_rcnt_il",
"total_bal_il",
"il_util",
"open_rv_12m",
"open_rv_24m",
"max_bal_bc",
"all_util",
"total_rev_hi_lim",
"inq_fi",
"total_cu_tl",
"inq_last_12m",
"acc_open_past_24mths",
"avg_cur_bal",
"bc_open_to_buy",
"bc_util",
"chargeoff_within_12_mths",
"delinq_amnt",
"mo_sin_old_il_acct",
"mo_sin_old_rev_tl_op",
"mo_sin_rcnt_rev_tl_op",
"mo_sin_rcnt_tl",
"mort_acc",
"mths_since_recent_bc",
"mths_since_recent_bc_dlq",
"mths_since_recent_inq",
"mths_since_recent_revol_delinq",
"num_accts_ever_120_pd",
"num_actv_bc_tl",
"num_actv_rev_tl",
"num_bc_sats",
"num_bc_tl",
"num_il_tl",
"num_op_rev_tl",
"num_rev_accts",
"num_rev_tl_bal_gt_0",
"num_sats",
"num_tl_120dpd_2m",
"num_tl_30dpd",
"num_tl_90g_dpd_24m",
"num_tl_op_past_12m",
"pct_tl_nvr_dlq",
"percent_bc_gt_75",
"pub_rec_bankruptcies",
"tax_liens",
"tot_hi_cred_lim",
"total_bal_ex_mort",
"total_bc_limit",
"total_il_high_credit_limit",
"verification_status_None",
"verification_status_Not Verified",
"verification_status_Source Verified",
"verification_status_Verified",
"term_ 36 months",
"term_ 60 months",
"term_None",
"application_type_INDIVIDUAL",
"application_type_JOINT",
"application_type_None",
"initial_list_status_None",
"initial_list_status_f",
"initial_list_status_w",
"purpose_None",
"purpose_car",
"purpose_credit_card",
"purpose_debt_consolidation",
"purpose_educational",
"purpose_home_improvement",
"purpose_house",
"purpose_major_purchase",
"purpose_medical",
"purpose_moving",
"purpose_other",
"purpose_renewable_energy",
"purpose_small_business",
"purpose_vacation",
"purpose_wedding",
"emp_length_1 year",
"emp_length_10+ years",
"emp_length_2 years",
"emp_length_3 years",
"emp_length_4 years",
"emp_length_5 years",
"emp_length_6 years",
"emp_length_7 years",
"emp_length_8 years",
"emp_length_9 years",
"emp_length_< 1 year",
"emp_length_None",
"emp_length_n/a",
"home_ownership_ANY",
"home_ownership_MORTGAGE",
"home_ownership_NONE",
"home_ownership_None",
"home_ownership_OTHER",
"home_ownership_OWN",
"home_ownership_RENT",
"addr_state_AK",
"addr_state_AL",
"addr_state_AR",
"addr_state_AZ",
"addr_state_CA",
"addr_state_CO",
"addr_state_CT",
"addr_state_DC",
"addr_state_DE",
"addr_state_FL",
"addr_state_GA",
"addr_state_HI",
"addr_state_IA",
"addr_state_ID",
"addr_state_IL",
"addr_state_IN",
"addr_state_KS",
"addr_state_KY",
"addr_state_LA",
"addr_state_MA",
"addr_state_MD",
"addr_state_ME",
"addr_state_MI",
"addr_state_MN",
"addr_state_MO",
"addr_state_MS",
"addr_state_MT",
"addr_state_NC",
"addr_state_ND",
"addr_state_NE",
"addr_state_NH",
"addr_state_NJ",
"addr_state_NM",
"addr_state_NV",
"addr_state_NY",
"addr_state_None",
"addr_state_OH",
"addr_state_OK",
"addr_state_OR",
"addr_state_PA",
"addr_state_RI",
"addr_state_SC",
"addr_state_SD",
"addr_state_TN",
"addr_state_TX",
"addr_state_UT",
"addr_state_VA",
"addr_state_VT",
"addr_state_WA",
"addr_state_WI",
"addr_state_WV",
"addr_state_WY",

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()